## **Importing Libraries**

In [168]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

---
## **Exercise 1**
### 1.1. Function to test if a graph is regular

In [169]:
def test_regular(G: nx.Graph | nx.DiGraph) -> bool:
    degrees = [d for n, d in G.degree()]
    return len(set(degrees)) == 1

### 2.2. Testing the function

In [170]:
G = nx.Graph([(1, 2), (2, 3), (3, 1)])
print(f"The graph is{' not' if not test_regular(G) else ''} regular")

The graph is regular


---
## **Exercise 2**

### 2.1. Constructing the requested graph

In [171]:
G = nx.DiGraph([
    ('a', 'b'),
    ('b', 'a'),
    ('b', 'c'),
    ('c', 'b'),
    ('a', 'c')
])

### 2.2. Graph path operations
#### 2.2.1. Getting the adjacency matrix of the constructed graph

In [172]:
M = nx.to_numpy_array(G)

#### 2.2.2. Matrix power

In [173]:
print(f"M^2 = \n{np.linalg.matrix_power(M, 2)}\n")
print(f"M^3 = \n{np.linalg.matrix_power(M, 3)}\n")
print(f"M^4 = \n{np.linalg.matrix_power(M, 4)}\n")
print(f"M + M^2 + M^3 + M^4 = \n{M + np.linalg.matrix_power(M, 2) + np.linalg.matrix_power(M, 3) + np.linalg.matrix_power(M, 4)}\n")

M^2 = 
[[1. 1. 1.]
 [0. 2. 1.]
 [1. 0. 1.]]

M^3 = 
[[1. 2. 2.]
 [2. 1. 2.]
 [0. 2. 1.]]

M^4 = 
[[2. 3. 3.]
 [1. 4. 3.]
 [2. 1. 2.]]

M + M^2 + M^3 + M^4 = 
[[4. 7. 7.]
 [4. 7. 7.]
 [3. 4. 4.]]



#### 2.2.3. Getting how many paths of length 4 from a to b

In [174]:
print(f"There is {int(np.linalg.matrix_power(M, 4)[0, 1])} paths of length 4 to go from a to b\n")

There is 3 paths of length 4 to go from a to b



#### 2.2.4. Extracting the paths of length 4 from a to b

##### 2.2.4.1. Making a recursive function that returns paths (and path count) of certain length going from a node to another

In [175]:
def extract_paths(G: nx.Graph | nx.DiGraph, start_endpoint: any, end_endpoint: any, path_count: int) -> tuple[list[list], int]:
    if len(G[start_endpoint]) == 0 or len(list(G.predecessors(end_endpoint))) == 0 or path_count == 0:
        raise ValueError("Error")
    
    if path_count == 1:
        if end_endpoint in list(G[start_endpoint]):
            return ([[start_endpoint, end_endpoint]], 1)
        else:
            return ([], 0)
        
    paths = []
    
    for node in list(G[start_endpoint]):
        temp_paths, _ = extract_paths(G, node, end_endpoint, path_count - 1)
        for path in temp_paths:
            paths.append([start_endpoint] + path)

    return (paths, len(paths))

##### 2.2.4.2. Applying `extract_paths` to extract paths of length 4 going from a to b

In [176]:
paths, path_count = extract_paths(G, 'a', 'b', 4)
print(f"There are {path_count} paths, and they are:")

for path in paths:
    print(" -> ".join(path))

There are 3 paths, and they are:
a -> b -> a -> c -> b
a -> c -> b -> a -> b
a -> c -> b -> c -> b


##### 2.2.4.3. Extracting paths of length 4 from b to b

In [177]:
paths, path_count = extract_paths(G, 'b', 'b', 4)
print(f"There are {path_count} paths, and they are:")

for path in paths:
    print(" -> ".join(path))

There are 4 paths, and they are:
b -> a -> b -> a -> b
b -> a -> b -> c -> b
b -> c -> b -> a -> b
b -> c -> b -> c -> b


##### 2.2.4.4. Extracting paths of length <= 4 from a to c

In [178]:
paths = []

for i in range(1, 5):
    temp_paths, _ = extract_paths(G, 'a', 'c', i)
    paths += temp_paths
    
path_count = len(paths)

print(f"There are {path_count} paths of length <= 4 from 'a' to 'c', they are:")

for path in paths:
    print(" -> ".join(path))

There are 7 paths of length <= 4 from 'a' to 'c', they are:
a -> c
a -> b -> c
a -> b -> a -> c
a -> c -> b -> c
a -> b -> a -> b -> c
a -> b -> c -> b -> c
a -> c -> b -> a -> c


---

## **Exercise 4**
### 4.1. Implementing `row_sum_matrix`
`row_sum_matrix` is a function that returns a vector containing the sum of each row of a given matrix

In [179]:
def row_sum_matrix(M: list[list[int | float]] | np.ndarray) -> list[int | float]:
    if isinstance(M, np.ndarray):
        if M.ndim != 2:
            raise ValueError("M is not a 2D matrix")
        return M.sum(axis=1).tolist()
    
    return [sum(row) for row in M]

#### 4.1.1. Testing `row_sum_matrix`

In [ ]:
M = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

row_sum_matrix(M)

[6, 15, 24]

In [ ]:
M = np.array([[1, 7, 4],
              [6, 12, 7],
              [8, 2, 3]])

row_sum_matrix(M)

[12, 25, 13]

### 4.2. Implementing `in_degree`
`in_degree` is a function that returns the in-degree of each vertex of a matrix M

In [182]:
def in_degree(M: np.ndarray) -> list:
    if M.ndim != 2:
        raise ValueError("M is not a 2D matrix")
    return M.sum(axis=0).tolist()

#### 4.2.1. Testing `in_degree`

In [ ]:
M = np.array([[2, 5, 8],
              [9, 4, 3],
              [5, 1, 7]])

in_degree(M)

[16, 10, 18]