## **Importing Libraries**

In [67]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

---
## **Exercise 1**
### 1.1. Function to test if a graph is regular

In [68]:
def test_regular(G: nx.Graph | nx.DiGraph) -> bool:
    degrees = [d for n, d in G.degree()]
    return len(set(degrees)) == 1

### 2.2. Testing the function

In [69]:
G = nx.Graph([(1, 2), (2, 3), (3, 1)])
print(f"The graph is{' not' if not test_regular(G) else ''} regular")

The graph is regular


---
## **Exercise 2**

### 2.1. Constructing the requested graph

In [70]:
G = nx.DiGraph([
    ('a', 'b'),
    ('b', 'a'),
    ('b', 'c'),
    ('c', 'b'),
    ('a', 'c')
])

### 2.2. Graph path operations
#### 2.2.1. Getting the adjacency matrix of the constructed graph

In [71]:
M = nx.to_numpy_array(G)

#### 2.2.2. Matrix power

In [72]:
print(f"M^2 = \n{np.linalg.matrix_power(M, 2)}\n")
print(f"M^3 = \n{np.linalg.matrix_power(M, 3)}\n")
print(f"M^4 = \n{np.linalg.matrix_power(M, 4)}\n")
print(f"M + M^2 + M^3 + M^4 = \n{M + np.linalg.matrix_power(M, 2) + np.linalg.matrix_power(M, 3) + np.linalg.matrix_power(M, 4)}\n")

M^2 = 
[[1. 1. 1.]
 [0. 2. 1.]
 [1. 0. 1.]]

M^3 = 
[[1. 2. 2.]
 [2. 1. 2.]
 [0. 2. 1.]]

M^4 = 
[[2. 3. 3.]
 [1. 4. 3.]
 [2. 1. 2.]]

M + M^2 + M^3 + M^4 = 
[[4. 7. 7.]
 [4. 7. 7.]
 [3. 4. 4.]]



#### 2.2.3. Getting how many paths of length 4 from a to b

In [73]:
print(f"There is {int(np.linalg.matrix_power(M, 4)[0, 1])} paths of length 4 to go from a to b\n")

There is 3 paths of length 4 to go from a to b



#### 2.2.4. Extracting the paths of length 4 from a to b

##### 2.2.4.1. Making a recursive function that returns paths (and path count) of certain length going from a node to another

In [74]:
def extract_paths(G: nx.Graph | nx.DiGraph, start_endpoint: any, end_endpoint: any, path_count: int) -> tuple[list[list], int]:
    if len(G[start_endpoint]) == 0 or len(list(G.predecessors(end_endpoint))) == 0 or path_count == 0:
        raise ValueError("Error")
    
    if path_count == 1:
        if end_endpoint in list(G[start_endpoint]):
            return ([[start_endpoint, end_endpoint]], 1)
        else:
            return ([], 0)
        
    paths = []
    
    for node in list(G[start_endpoint]):
        temp_paths, _ = extract_paths(G, node, end_endpoint, path_count - 1)
        for path in temp_paths:
            paths.append([start_endpoint] + path)

    return (paths, len(paths))

##### 2.2.4.2. Applying `extract_paths` to extract paths of length 4 going from a to b

In [75]:
paths, path_count = extract_paths(G, 'a', 'b', 4)
print(f"There are {path_count} paths, and they are:")

for path in paths:
    print(" -> ".join(path))

There are 3 paths, and they are:
a -> b -> a -> c -> b
a -> c -> b -> a -> b
a -> c -> b -> c -> b


##### 2.2.4.3. Extracting paths of length 4 from b to b

In [76]:
paths, path_count = extract_paths(G, 'b', 'b', 4)
print(f"There are {path_count} paths, and they are:")

for path in paths:
    print(" -> ".join(path))

There are 4 paths, and they are:
b -> a -> b -> a -> b
b -> a -> b -> c -> b
b -> c -> b -> a -> b
b -> c -> b -> c -> b


##### 2.2.4.4. Extracting paths of length <= 4 from a to c

In [77]:
paths = []

for i in range(1, 5):
    temp_paths, _ = extract_paths(G, 'a', 'c', i)
    paths += temp_paths
    
path_count = len(paths)

print(f"There are {path_count} paths of length <= 4 from 'a' to 'c', they are:")

for path in paths:
    print(" -> ".join(path))

There are 7 paths of length <= 4 from 'a' to 'c', they are:
a -> c
a -> b -> c
a -> b -> a -> c
a -> c -> b -> c
a -> b -> a -> b -> c
a -> b -> c -> b -> c
a -> c -> b -> a -> c


---